// import { cookieToInitialState } from 'wagmi'
// import { config } from './config'
// import { ContextProvider } from './context'
// import { ReactNode } from 'react';
// // Define metadata directly
// const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

// export default function RootLayout({ children }: { children: ReactNode }) {
//   const initialState = cookieToInitialState(config, ''); 
//   return (
//     <html lang="en">
//       <body>
//         <ContextProvider initialState={initialState}>{children}</ContextProvider>
//       </body>
//     </html>
//   )
// }
import { cookieToInitialState } from 'wagmi'
import { config } from './config'
import { ContextProvider } from './context'
import { ReactNode } from 'react';

// Define metadata directly
const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const initialState = cookieToInitialState(config, ''); 
  return (
    <ContextProvider initialState={initialState}>{children}</ContextProvider>
  )
}

